print('asfsdafasdfasdfsadfsdafasdf')
print('asfsdafasdfasdfsadfsdafasdf')
print('asfsdafasdfasdfsadfsdafasdf')
print('asfsdafasdfasdfsadfsdafasdf')
print('asfsdafasdfasdfsadfsdafasdf')
print('sadfsadsadasd')
print('sadfsadsadasd')
